# Generated by Django 4.1.3 on 2022-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full time', 'full_time'), ('Part time', 'part_time'), ('Freelance', 'freelance'), ('Internship', 'internship'), ('Termporary', 'termporary')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
