# Generated by Django 4.1.3 on 2022-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='file',
            field=models.FileField(default='u', upload_to='cves/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='image',
            field=models.ImageField(default='e', upload_to='media/'),
            preserve_default=False,
        ),
    ]
