# Generated by Django 4.1.3 on 2022-11-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_candidates_file_candidates_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='slug',
            field=models.SlugField(default='r'),
            preserve_default=False,
        ),
    ]
