# Generated by Django 4.1.3 on 2022-12-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_candidates_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidates',
            options={'ordering': ['-id']},
        ),
    ]
