# Generated by Django 4.1.3 on 2022-12-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_candidates_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
