# Generated by Django 4.1.3 on 2022-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_description_alter_blog_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='e'),
            preserve_default=False,
        ),
    ]
